### ISSUE TITLE
Cannot login at Google Drive

### ISSUE THREAD

**Issue by DerSaxxe** [KumarManas04/NotesSync#4]
How to reproduce:

1. Click at Settings - Login
2. Click at Google Drive.
3. Now a window appers to choose the account. Click on your account.
4. The window is closing and nothing happens

**Comment by KumarManas04** [comment]
Did you follow step 3 from https://github.com/KumarManas04/NotesSync#how-to-build-the-project
completely? It seems that you forgot to add your build's SHA-1 key to the credentials screen of the Google Drive API console.

**Comment by DerSaxxe** [comment]
Yes, this was my mistake. So we can close this issue. Thank you
