### ISSUE TITLE
Problems with taking a photo note

### ISSUE THREAD

**Issue by DerSaxxe** [KumarManas04/NotesSync#6]
If you take a photo outside of a note (new photo note button at the bottom right) most times the note doesn't appear, sometimes with a big delay.

**Comment by KumarManas04** [comment]
This seems to be an issue of storage permission on some devices. 
For access to the app's own internal storage there is only the need to mention the permission in the manifest and no need of granting the permission but some devices encounter a SecurityException in this case. 
So please give the storage permission manually to the app(via system settings) and check if the problem continues.
If this solves the problem then in the future release we can ask the users to give the storage permission to the app.

**Comment by DerSaxxe** [comment]
Yes I had to give the storage permission manually. Now it works but with a very slow performance. It takes 20 seconds after taking a photo til the toast message "Processing image" appears. My phone: Mi 9t Pro

**Comment by KumarManas04** [comment]
The problem has been fixed.
